config/routes.rb
Rails.application.routes.draw do
  resources :docs do
    get :sign, on: :member
    get :refuse, on: :member
    get :match, on: :member
    patch :on_agree, on: :member
  end
  get 'my_docs', to: 'docs#my_docs', as: 'my_docs'
  get 'on_sign', to: 'docs#on_sign_docs', as: 'on_sign'
  get 'on_match', to: 'docs#on_match_docs', as: 'on_match'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  get 'hello/index'
  root to: 'hello#index'
end

app/models/doc.rb
class Doc < ApplicationRecord
  include ImageUploader[:image]
  before_create :set_params
  validates :title, :text, presence: true
  belongs_to :executor, class_name: "User"
  belongs_to :initiator, class_name: "User"
  belongs_to :signer, class_name: "User"
  belongs_to :destination, class_name: "User"
  has_and_belongs_to_many :users
  has_many :matches, dependent: :destroy
  has_many :matchers, through: :matches, source: :user



  def set_params
    if Doc.last
      last_doc = Doc.last.id
    else
      last_doc = 0
    end
    self.number = sprintf("%03d", last_doc+1) + '-055'
    self.signed, self.done = false, false
    if !(self.matchers.any?)
      self.agreed = true
    else
      self.agreed = false
    end
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy, :sign, :refuse, :match, :on_agree]
  before_action :set_on_match_docs
  before_action :is_signer, only: [:sign, :refuse]
  before_action :is_matcher, only: :match
  # GET /docs
  # GET /docs.json

  def on_agree
    @doc.update(agreed: false)
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_users
  end

  def my_docs
    @active = 3
    @my_docs = Doc.where(initiator: current_user)
  end

  def on_sign_docs
    @active = 2
    @osdocs = Doc.where(signer: current_user, signed: false, refused: false, agreed: true)
  end

  def on_match_docs
    @active = 4
  end

  def refuse
    @doc.update!(refused: true)
    @doc.logs += "Документу №#{@doc.number} отказано в подписи #{DateTime.now}.<br> Подписант: #{@doc.signer.name_with_initial} <br>"
    @doc.save
    redirect_to root_path, notice: "Документ будет направлен обратно инициатору!"
  end

  def match
    Match.find_by(doc_id: @doc.id, user_id: current_user.id).update(match: true)
    @doc.logs += "Документ №#{@doc.number} согласован с #{current_user.name_with_initial} #{DateTime.now}.<br>"
    @doc.save
    unless Match.where(doc_id: @doc.id, match: false).any?
      @doc.update(agreed: true)
      redirect_to root_path, notice: "Документ согласован, и отправлен на подпись"
    else
      redirect_to root_path, notice: "Документ согласован с вами, и ожидает согласование с другими людьми"
    end
  end

  def sign
    @doc.update!(signed: true, refused: false)
    @doc.logs += "Документ №#{@doc.number} подписан #{DateTime.now}.<br> Подписант: #{@doc.signer.name_with_initial} <br>"
    @doc.save
    redirect_to root_path, notice: "Документ успешно подписан!"
  end

  def index
    @active = 1
    @docs = Doc.all.order(:number)
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
  end

  # GET /docs/new
  def new
    $matcherid = 0
    @doc = Doc.new
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = Doc.new(doc_params)
    @doc.initiator = User.find(session[:user_id])
    @doc.destination = User.first
    @doc.executor = User.first
    @doc.logs = "<br>Документ создан #{DateTime.now} <br> Инициатор документа: #{current_user.name_with_initial} <br> "
    respond_to do |format|
      if @doc.save
        if @doc.matchers.any?
          format.html { redirect_to @doc, notice: 'Документ успешно создан и отправлен на согласование, вы можете отслеживать его состояние во вкладке "Мои документы".' }
        else
          format.html { redirect_to @doc, notice: 'Документ успешно создан и отправлен на подпись, вы можете отслеживать его состояние во вкладке "Мои документы".' }
        end
        format.json { render :show, status: :created, location: @doc }
      else
        format.html { render :new }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docs/1
  # PATCH/PUT /docs/1.json
  def update
    @doc.refused = false
    @doc.logs += "Документ отредактирован #{DateTime.now}. <br> Документ повторно отправлен на подпись #{@doc.signer.name_with_initial}<br>"
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc.destroy
    respond_to do |format|
      format.html { redirect_to docs_url, notice: 'Документ был удалён' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def is_signer
      if current_user == @doc.signer
        true
      else
        false
        redirect_to root_path, notice: "Вы не имеете прав подписывать или отказывать в подписи этого документа"
        end
    end
    def set_doc
      @doc = Doc.find(params[:id])
    end

    def set_on_match_docs
      matches = Match.where(user_id: current_user, match: false)
      ids = []
      matches.each do |match|
        ids << match.doc_id
      end
        @omdocs = Doc.find(ids)
    end

    def is_matcher
      if Match.where(user_id: current_user.id, doc_id: @doc.id, match: false).any?
        true
      else
        false
        redirect_to root_path, notice: "Вы уже согласовывали этот документ или вас нет в списке согласующих!"
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def doc_params
      params.require(:doc).permit(:title, :text, :number, :logs, :signed, :agreed, :resolution, :done, :signer_id, :destination_id, :executor_id, :image, :matcher_ids => [])
    end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_form.html.slim
= simple_form_for @doc, html: {class: "form-horizontal", role: "form"} do |f|
  - if @doc.errors.any?
    #error_explanation
      h2 = "#{pluralize(@doc.errors.count, "error")} prohibited this doc from being saved:"
      ul
        - @doc.errors.full_messages.each do |message|
          li = message
  = f.label :title
  = f.text_field :title, class: "form-control", placeholder: "Введите название"
  br
  = f.label :text
  = f.text_area :text, class: "form-control", placeholder: "Введите текст документа", rows: "3"
  br
  = f.label :signer
  = f.grouped_collection_select :signer_id, Subdivision.all, :users, :name, :id, :name_with_initial, {:prompt => "Пожалуйста, выберите подписаната"}, {:class => 'form-control selectpicker', "data-live-search" => "true"}
  br
  /.comments
    = f.label :executor
    = f.grouped_collection_select :id, Subdivision.all, :users, :name, :id, :name_with_initial, {:prompt => "Пожалуйста, выберите исполнителя"}, {:class => 'form-control selectpicker', "data-live-search" => "true"}
    br
    = f.label :destination
    .matchers
    = f.grouped_collection_select :matchers, Subdivision.all, :users, :name, :id, :name_with_initial, {}, {:class => 'form-control', name: "doc[matcher_ids][]", :multiple=>true}

  br
  = f.label :image_data
  = f.hidden_field :image, value: f.object.cached_image_data
  = f.file_field :image, class: "file"
  br
  = f.submit class: "btn btn-default", value: "На подпись!"

app/views/docs/edit.html.slim
h1 Editing doc

== render 'form'

= link_to 'Show', @doc
'  |
= link_to 'Back', docs_path

app/views/docs/index.html.slim
h1 Все документы

table class="table table-striped"
  thead
    tr
      th Название
      th Номер
      th Подписан
      th Согласован
      th Выполнен
      th Вложение
      th Создан
      th
      th
      th

  tbody
    - @docs.each do |doc|
      tr
        td = doc.title
        td = doc.number
        td = "√" if doc.signed
        td = "√" if doc.agreed
        td = "√" if doc.done
        td = link_to "Есть", doc.image_url if doc.image.present?
        td = doc.created_at
        td = link_to 'Показать', doc
        - unless doc.signed
          td = link_to 'Редактировать', edit_doc_path(doc)
        -else
          td Редактирование запрещено.
        td = link_to 'Удалить', doc, data: { confirm: 'Вы уверены?' }, method: :delete
br

= link_to 'Новый документ', new_doc_path

app/views/docs/my_docs.html.slim
- unless @my_docs.empty?
  h1 Мои документы
  table class="table table-striped"
    thead
      tr
        th Название
        th Номер
        th Подписан
        th Не подписан
        th Согласован
        th Выполнен
        th
        th
        th
        th Вложение

    tbody
      - @my_docs.each do |doc|
        tr
          td = doc.title
          td = doc.number
          td = "√" if doc.signed
          td = "√" if doc.refused
          td = "√" if doc.agreed
          td = "√" if doc.done
          td = link_to 'Показать', doc
          - unless doc.signed
            td = link_to 'Редактировать', edit_doc_path(doc)
          -else
            td Редактирование запрещено.
          td = link_to 'Удалить', doc, data: { confirm: 'Вы уверены?' }, method: :delete
          td = link_to "Есть", doc.image_url if doc.image.present?
- else
  h1 Вы не создали не одного документа!

app/views/docs/new.html.slim
h1 Новый документ

== render 'form'

= link_to 'Back', docs_path

app/views/docs/on_match_docs.html.slim
- unless @omdocs.empty?
  h1 Документы на согласование
  table class="table table-striped"
    thead
      tr
        th Название
        th Номер
        th Подписан
        th Согласован
        th Выполнен
        th
        th
        th
        th Вложение
        th

    tbody
      - @omdocs.each do |doc|
        tr
          td = doc.title
          td = doc.number
          td = "√" if doc.signed
          td = "√" if doc.agreed
          td = "√" if doc.done
          td = link_to 'Показать', doc
          td = link_to 'Редактировать', edit_doc_path(doc)
          td = link_to 'Удалить', doc, data: { confirm: 'Вы уверены?' }, method: :delete
          td = link_to "Есть", doc.image_url if doc.image.present?
          td = link_to "Согласовать", match_doc_path(doc.id), class: "btn btn-success", role: "button"
- else
  h1 Нет документов на согласование!

app/views/docs/on_sign_docs.html.slim
- unless @osdocs.empty?
  h1 Документы на подпись
  table class="table table-striped"
    thead
      tr
        th Название
        th Номер
        th Подписан
        th Согласован
        th Выполнен
        th
        th
        th
        th Вложение
        th

    tbody
      - @osdocs.each do |doc|
        tr
          td = doc.title
          td = doc.number
          td = "√" if doc.signed
          td = "√" if doc.agreed
          td = "√" if doc.done
          td = link_to 'Показать', doc
          td = link_to 'Редактировать', edit_doc_path(doc)
          td = link_to 'Удалить', doc, data: { confirm: 'Вы уверены?' }, method: :delete
          td = link_to "Есть", doc.image_url if doc.image.present?
          - if doc.agreed
            td = link_to "Подписать", sign_doc_path(doc.id), class: "btn btn-success", role: "button"
          - else
            td Документу требуется согласование!
- else
  h1 Нет документов на подпись!

app/views/docs/show.html.slim
.btn-group.btn-group-lg
  = link_to 'Редактировать', edit_doc_path(@doc), class: "btn btn-default" unless @doc.signed
  = link_to 'Назад', docs_path, class: "btn btn-default"

p
  strong Тема:
  = @doc.title
p
  strong Текст:
  = @doc.text
p
  strong Номер документа:
  = @doc.number
p
  strong Подписан:
  = @doc.signed
p
  strong Согласован:
  = @doc.agreed
p
  strong Резолюция:
  = @doc.resolution
p
  strong Выполнен:
  = @doc.done
p
  strong Протокол выполнения:
  = sanitize(@doc.logs)
-unless @doc.agreed
  p
    strong Требуется согласование с:
    br
    - @doc.matchers.each do |matcher|
      = matcher.name_with_initial
      br
      br
-else
  p
  - if !(@doc.signed) && @doc.signer == current_user
    = form_tag on_agree_doc_path, method: "patch" do
      strong Если документ требует согласования перед подписью, выберите согласующих, и нажмите "Отправить документ на согласование"
      = grouped_collection_select :doc, :matchers, Subdivision.all, :users, :name, :id, :name_with_initial, {}, {:class => 'form-control', name: "doc[matcher_ids][]", :multiple=>true}
      p
      = link_to "Подписать", sign_doc_path(@doc.id), class: "btn btn-success", role: "button"
      = submit_tag "Отправить документ на согласование", class: "btn btn-primary"
      = link_to "Отказать", refuse_doc_path(@doc.id), class: "btn btn-danger", role: "button"
    p
    p