config/routes.rb
Rails.application.routes.draw do
  resources :docs do
    get :sign, on: :member
    get :refuse, on: :member
    get :match, on: :member
    patch :on_agree, on: :member
  end
  get 'my_docs', to: 'docs#my_docs', as: 'my_docs'
  get 'on_sign', to: 'docs#on_sign_docs', as: 'on_sign'
  get 'on_match', to: 'docs#on_match_docs', as: 'on_match'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  get 'hello/index'
  root to: 'hello#index'
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Домой', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="<%= "active" if @active == 1 %>"><%= link_to docs_path do %>
  Все документы
  <% end %></li>
<li class="<%= "active" if @active == 2 %>"><%= link_to on_sign_path do %>
  Документы на подпись
    <% on_sign_counter = Doc.where(signer: current_user, signed: false, refused: false, agreed: true).count %>
  <% if on_sign_counter != 0 %>
  <span class="badge"><%= on_sign_counter %></span>
  <% end %>
  <% end %></li>
  <li class="<%= "active" if @active == 3 %>"><%= link_to my_docs_path do %>
  Мои документы
  <% my_docs_counter = Doc.where(initiator: current_user, refused: true).count %>
  <% if my_docs_counter != 0 %><span class="badge"><%= my_docs_counter %></span>
  <% end %>
  <% end %></li>
<li class="<%= "active" if @active == 4 %>"><%= link_to on_match_path do %>
  Документы на согласование
  <% @omdocs? on_match_counter = @omdocs.count : on_match_counter = 0 %>
  <% if on_match_counter != 0 %>
  <span class="badge"><%= on_match_counter %></span>
  <% end %>
  <% end %></li>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Документооборот'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Документооборот'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield